#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#
#  ODPX.py

import random

def ODPX(p1, p2, k, n):
    I = [val for val in p1[:k] if val in p2[:k]]
    for i in range(0, k):
        if not (p1[i] in I):
            j = random.randrange(k, n)
            temp = p1[i]
            p1[i] = p1[j]
            p1[j] = temp
    J = p1[:k]
    for i in range(0, k):
        if not (p2[i] in I):
            j = random.randrange(k, n)
            while p2[j] in J:
                j = random.randrange(k, n)
            temp = p2[i]
            p2[i] = p2[j]
            p2[j] = temp
    q1 = p1[:k]
    q2 = q1
    q3 = p2[:k]
    q4 = q3
    L1 = []
    L2 = []
    for i in range(0, 2*(n - k)):
        if (i%2 == 1) is True:
            L1.append(p1[k + (i - 1)/2])
            L2.append(p2[k + (i - 1)/2])
        else:
            L1.append(p2[k - 1 + i/2])
            L2.append(p1[k - 1 + i/2])
    for i in range(0, 2*(n - k)):
        if not (L1[i] in q1):
            q1.append(L1[i])
        else:
            q2.append(L1[i])
        if not (L2[i] in q4):
            q4.append(L2[i])
        else:
            q3.append(L2[i])
    return q1, q2, q3, q4

def create_partitions(G, k, p):
    partitions = []
    free = []
    n = len(p)
    for i in range(k):
        partitions.append([p[i]])
        free.append(False)
    for i in range(k, n):
        free.append(True)
    someFree = True
    while someFree:
        someFree = False
        for i in range(k, n):
            if free[i]:
                smallest = float('inf')
                index = -1
                for l in range(k):
                    for j in G[p[i]]:
                        if j in partitions[l]:
                            if len(partitions[l]) < smallest:
                                smallest = len(partitions[l])
                                index = l
                if index == -1:
                    someFree = True
                else:
                    partitions[index].append(p[i])
                    free[i] = False
    return partitions

def main(args):
    G = [[1,2,3],[0,7,8],[0,3,7],[0,2,4,5],[3,5],[3,4,7],[7,8,10],[1,2,5,6],[1,6,9],[8,11],[6,11],[9,10]]
    k = 3
    p = (6,5,2,9,4,0,10,8,3,11,7,1)
    print create_partitions(G, k, p)
    n = 12
    q1, q2, q3, q4 = ODPX([5, 3, 7, 4, 11, 8, 2, 12, 1, 9, 6, 10], [7, 6, 3, 10, 5, 1, 11, 9, 4, 12, 8, 2], k, n)
    print q1
    print q2
    print q3
    print q4
    return 0

if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv))
